### ISSUE TITLE
playback-rate lower 0.626 seems to be supported in Chrome

### ISSUE THREAD

**Issue by AnWeber** [chrisguttandin/media-sync#17]
playback-rates lower 0.625 seems to be supported in Chrome. Why is this Range used for Chrome?

Test with CodeSandBox in Chrome v109
https://codesandbox.io/s/dazzling-chebyshev-ytsgz2

https://github.com/chrisguttandin/timingsrc/blob/master/src/functions/determine-supported-playback-rate-values.ts#L17

Thanks

**Comment by chrisguttandin** [comment]
Hi @AnWeber, many thanks for letting me know. It's actually a typo. It should be `0.0625` and not `0.625`.

The test which covers the behavior in Chrome is here: https://github.com/chrisguttandin/timingsrc/blob/490d69849c98859e7e12978745df932064257c59/test/expectation/chrome/media-element.js#L11-L17
I just forgot a `0`. :-(

**Comment by chrisguttandin** [comment]
Thanks again @AnWeber, the fix got published as v1.2.14.

**Comment by AnWeber** [comment]
Great. Thanks
