### ISSUE TITLE
Weird behaviour on video ended

### ISSUE THREAD

**Issue by marcusand** [chrisguttandin/media-sync#4]
Hey :) 

Unfortunately I am experiencing a new issue that occurs when a video has ended.  Depending on the video the `ended`
event is dispatched multiple times together with some visual jumping. 

Code:
```js

import { TimingProvider } from "timing-provider";
import { TimingObject } from "timing-object";
import { setTimingsrc } from "timingsrc";

const video1 = document.querySelector("#video1");

const timingProvider = new TimingProvider("ws://localhost:3002");
const timingObject = new TimingObject(timingProvider);

video1.addEventListener("ended", console.log);

timingObject.addEventListener("readystatechange", () => {
  if (timingObject.readyState === "open") {
    setTimingsrc(video1, timingObject);
    timingObject.update({ velocity: 1 });
  }
});

```

Result:

https://user-images.githubusercontent.com/28539818/114894885-4ee10580-9e0f-11eb-9920-dd33a16eb470.mov

Any ideas?

**Comment by chrisguttandin** [comment]
Thanks a lot for reporting this. There was a flaw in the logic which updates the media element. I hope it's fixed now.

**Comment by marcusand** [comment]
Nice! Will check asap
